### PR TITLE
Added generated levels for stress testing

### PR DESCRIPTION
**Pull request by lastedge**

### CODE REVIEW

**Comment by lastedge** [comment]
Issues:
1. LT depends on map size.
2. Performance degrades with level size.

**Comment by rexim** [comment]
@lastedge 

> Issues:
> 1. LT depends on map size.
> 2. Performance degrades with level size.

Sorry, this is not how you submit issues. Please check out the [GitHub Documentation](https://help.github.com/articles/creating-an-issue/) to learn how to submit issues properly.

Thanks for the Pull Request.

**Comment by lastedge** [comment]
> Sorry, your PR exceeds the size threshold by a huge margin. Check out [Contribution Rules](https://github.com/tsoding/nothing/blob/b876599dd05e33c80c48946788b3b7480e1e7379/CONTRIBUTING.md#pull-requests) on PRs.

Pull request is well within thresholds mandated in [Contribution Rules](https://github.com/tsoding/nothing/blob/b876599dd05e33c80c48946788b3b7480e1e7379/CONTRIBUTING.md#pull-requests): 3 new files. No file size threshold specified.

> Sorry, this is not how you submit issues. Please check out the [GitHub Documentation](https://help.github.com/articles/creating-an-issue/) to learn how to submit issues properly.

Comment not an issue submission, simply a reference for why the files were submitted.

**Comment by rexim** [comment]
> Pull request is well within thresholds mandated in [Contribution Rules](https://github.com/tsoding/nothing/blob/b876599dd05e33c80c48946788b3b7480e1e7379/CONTRIBUTING.md#pull-requests): 3 new files. No file size threshold specified.

Sorry, it is not. You changed 78394 lines. 

2019-01-14-210935_3286x1080_scrot

This fact is not disputable and continued attempts to play on rules interpretation instead of fixing the actual problem with the suggested approach (by submitting a script) will result in deeming this PR a spam and blocking you from contributing to @tsoding projects in the future.

I really wanna have a constructive conversion in the issue trackers. And you are not helping.

**Comment by lastedge** [comment]
> Sorry, it is not. You changed 78394 lines.
> 
> 2019-01-14-210935_3286x1080_scrot

No lines have been changed, they are entirely new files. If new files over 300 lines are not to be accepted this should be made clear in the contribution rules.
 
> This fact is not disputable and continued attempts to play on rules interpretation instead of fixing the actual problem with the suggested approach (by submitting a script) will result in deeming this PR a spam and blocking you from contributing to @tsoding projects in the future.
> 
> I really wanna have a constructive conversion in the issue trackers. And you are not helping.

Petty replies to pull requests do not lead to constructive conversations. A pull request with the generation program would have followed after the generation code had been cleaned up to fit within project.

Hostility is not conducive to positive contributions. Your project though, so do as you please!

**Comment by rexim** [comment]
> No lines have been changed, they are entirely new files. If new files over 300 lines are not to be accepted this should be made clear in the contribution rules.

Yeah, after a second thought it does make sense to clarify it a little bit. dc9a1e44879032bdc78ec8447103d9f872b2f96f

> A pull request with the generation program would have followed after the generation code had been cleaned up to fit within project.

Nice! Please submit that Pull Request! I will be happy to merge it!

**Pull request closed without merging**
